import SwiftUI
// Terms & Conditions View
struct TermsAndConditionsView: View {
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    Text("Terms and Conditions")
                        .font(.largeTitle)
                        .fontWeight(.bold)
                        .padding(.bottom, 8)
                    
                    Text("Last Updated: December 2024")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                    
                    Group {
                        section("Agreement to Terms", content: """
                        By downloading, installing, or using Lumen ("the App"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the App.
                        """)
                        
                        section("Description of Service", content: """
                        Lumen is a local AI chat application that allows you to run AI language models locally on your device, have conversations with AI models, import and manage AI models, and store conversation history locally.
                        """)
                        
                        section("Use License", content: """
                        You are granted a limited, non-exclusive, non-transferable license to download and install the App on your personal devices and use it for personal, non-commercial purposes.
                        
                        You may not reverse engineer, decompile, or disassemble the App, remove or alter any copyright notices, use the App for illegal purposes, or distribute the App without permission.
                        """)
                        
                        section("AI Models and Content", content: """
                        You are responsible for ensuring you have the right to use any AI models you import. Models may be subject to their own licenses. Content generated by AI models may not always be accurate or appropriate. You are responsible for reviewing and verifying any AI-generated content.
                        
                        You agree not to use the App to generate illegal content, violate intellectual property rights, harass others, or violate any applicable laws.
                        """)
                        
                        section("Disclaimer of Warranties", content: """
                        THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
                        """)
                        
                        section("Limitation of Liability", content: """
                        TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, LOSS OF DATA, PROFITS, OR BUSINESS OPPORTUNITIES, OR DAMAGES RESULTING FROM USE OR INABILITY TO USE THE APP.
                        """)
                    }
                }
                .padding()
            }
            .navigationTitle("Terms & Conditions")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") { dismiss() }
                }
            }
            #else
            .toolbar {
                ToolbarItem(placement: .primaryAction) {
                    Button("Done") { dismiss() }
                }
            }
            #endif
        }
    }
    
    private func section(_ title: String, content: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title)
                .font(.headline)
                .fontWeight(.semibold)
            Text(content)
                .font(.body)
                .foregroundStyle(.secondary)
        }
    }
}

// Privacy Policy View
struct PrivacyPolicyView: View {
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    Text("Privacy Policy")
                        .font(.largeTitle)
                        .fontWeight(.bold)
                        .padding(.bottom, 8)
                    
                    Text("Last Updated: December 2024")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                    
                    Group {
                        section("Introduction", content: """
                        Lumen is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our application.
                        """)
                        
                        section("Information We Collect", content: """
                        Lumen is designed with privacy in mind. All data is stored locally on your device:
                        
                        • Conversation History: Stored locally using encrypted storage (Keychain)
                        • AI Models: Stored locally in your chosen directory
                        • Settings: Stored locally on your device
                        
                        We do NOT collect, transmit, or share any personal information, conversation content, usage analytics, device identifiers, location data, or any other user data.
                        """)
                        
                        section("How We Use Your Information", content: """
                        Since we do not collect any information, we do not use, share, or sell any user data. All processing is performed locally on your device.
                        """)
                        
                        section("Data Security", content: """
                        • Encryption: Conversation data is encrypted using AES-256-GCM encryption and stored securely in the iOS/macOS Keychain
                        • Local Storage: All data remains on your device and is never transmitted over the network
                        • No Cloud Sync: We do not sync your data to any cloud service
                        """)
                        
                        section("Your Rights", content: """
                        Since all data is stored locally on your device, you have complete control:
                        
                        • Access: All your data is accessible through the app interface
                        • Deletion: You can delete conversations at any time
                        • Export: You can export your conversations using the built-in export feature
                        • Control: You control where models are stored
                        """)
                        
                        section("Summary", content: """
                        Lumen stores all data locally on your device. We do not collect, transmit, or share any user data. Your privacy is our priority.
                        """)
                    }
                }
                .padding()
            }
            .navigationTitle("Privacy Policy")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") { dismiss() }
                }
            }
            #else
            .toolbar {
                ToolbarItem(placement: .primaryAction) {
                    Button("Done") { dismiss() }
                }
            }
            #endif
        }
    }
    
    private func section(_ title: String, content: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title)
                .font(.headline)
                .fontWeight(.semibold)
            Text(content)
                .font(.body)
                .foregroundStyle(.secondary)
        }
    }
}

// Licenses View
struct LicensesView: View {
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        NavigationStack {
            List {
                Section {
                    licenseItem(
                        name: "MLX Swift",
                        license: "Apache License 2.0",
                        url: "https://github.com/ml-explore/mlx-swift"
                    )
                    licenseItem(
                        name: "MLXLLM",
                        license: "MIT License",
                        url: "https://github.com/ml-explore/mlx-swift"
                    )
                    licenseItem(
                        name: "PythonKit",
                        license: "Apache License 2.0",
                        url: "https://github.com/pvieito/PythonKit"
                    )
                } header: {
                    Text("Open Source Libraries")
                } footer: {
                    Text("This app uses open-source software. See individual licenses for details.")
                }
            }
            .navigationTitle("Licenses")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("Done") { dismiss() }
                }
            }
            #else
            .toolbar {
                ToolbarItem(placement: .primaryAction) {
                    Button("Done") { dismiss() }
                }
            }
            #endif
        }
    }
    
    private func licenseItem(name: String, license: String, url: String) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(name)
                .font(.headline)
            Text(license)
                .font(.caption)
                .foregroundStyle(.secondary)
            Text(url)
                .font(.caption2)
                .foregroundStyle(.blue)
        }
        .padding(.vertical, 4)
    }
}

